version: "3.7"

services:
  database:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=api_rest_typescript
    volumes:
      - pg_data:/data/postgres

volumes:
  pg_data:
    driver: local
